---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-7.0
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[mongodb::default]
    attributes:

  - name: server
    run_list:
      - recipe[mongodb::server]
    attributes:

  - name: shell
    run_list:
      - recipe[mongodb::shell]
    attributes:

  - name: tools
    run_list:
      - recipe[mongodb::tools]
    attributes:

  - name: mongos
    run_list:
      - recipe[mongodb::mongos]
    attributes:
  
  - name: remove
    run_list:
      - recipe[mongodb::remove]
    attributes:

