name               'mongodb'
version            '0.0.3'
maintainer         'Josh Wisely'
maintainer_email   'joshwisely@gmail.com'
supports           'centos'
depends            'yum', '~> 3.8.1'
depends            'selinux', '~> 0.9.0'
